### ISSUE TITLE
401 for push action, and OK for PR action

### ISSUE THREAD

**Issue by bomzheg** [Schneegans/dynamic-badges-action#38]
i have successful Action when it triggered from PR https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256
```
Run schneegans/dynamic-badges-action@v1.7.0
  with:
    auth: ***
    gistID: 99469cb5f8a18784c1f03d[2](https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256#step:8:2)29a799427
    filename: bage.json
    label: Coverage Report
    message: 7[3](https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256#step:8:3)%
    color: yellow
    namedLogo: python
    host: https://api.github.com/gists/
    forceUpdate: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.10/x6[4](https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256#step:8:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.10/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.10/x[6](https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256#step:8:6)4
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.10/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.[10](https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256#step:8:10)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[11](https://github.com/bomzheg/Shvatka/actions/runs/11900528289/job/33161572256#step:8:11).10/x64/lib
Content did not change, not updating gist at bage.json.
```

but the same action from push to master got 401 https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399
```
Run schneegans/dynamic-badges-action@v1.7.0
  with:
    gistID: 99469cb5f8a18784c1f03d[2](https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399#step:8:2)29a799427
    filename: bage.json
    label: Coverage Report
    message: 7[3](https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399#step:8:3)%
    color: yellow
    namedLogo: python
    host: https://api.github.com/gists/
    forceUpdate: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.10/x6[4](https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399#step:8:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.10/x[6](https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399#step:8:6)4/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.[10](https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399#step:8:10)/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.[11](https://github.com/bomzheg/Shvatka/actions/runs/11900568388/job/33162074399#step:8:11).10/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.10/x64/lib
Error: Failed to get gist: 401 Unauthorized
```

the first have auth property, and the second doesn't.

my config is:
```yaml
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BAGE_GIST }}
          gistID: 99469cb5f8a18784c1f03d229a799427
          filename: bage.json
          label: Coverage Report
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
```

Can you help me?
