### ISSUE TITLE
"Bad credentials" bug

### ISSUE THREAD

**Issue by HydrolienF** [Schneegans/dynamic-badges-action#4]
I'm triing to update a test file with this github action but I still getting an error.

Is there something wrong in my file ?

**result when runing the actions**
```
Run Schneegans/dynamic-badges-action@v1.0.0
  with:
    gistID: 1db057b2a755ff6cfb841d987eeed3ab
    filename: test
    label: Test
    message: 98%
    color: green
result:{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

**.yml action file**
```
name: Update language value

on:
  push:
    branches:
    - "*"

jobs:
  updateValue:
    runs-on: ubuntu-latest
    steps:
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 1db057b2a755ff6cfb841d987eeed3ab
        filename: test
        label: Test
        message: 98%
        color: green
```
